# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/BuildingBlocks/BuildingBlocks" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Basket/Basket.API" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Catalog/Catalog.API" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Discount/Discount.gRPC" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Ordering/Ordering.API" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Ordering/Ordering.Application" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Ordering/Ordering.Domain" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Services/Ordering/Ordering.Infrastructure" # Location of package manifests
    schedule:
      interval: "weekly"
